Repository RockChinQ/revLibs, pull requests merged in 2023-05, with the labels that each got.

#156 [Feat] New Bing不再需要鉴权
  README.md
  pkg/process/impls/edgegpt.py
  pkg/process/revss.py
  requirements.txt
Labels: compatibility

#157 [Feat] 现在要求为hugchat提供Cookies
  pkg/process/impls/hugchat.py
Labels: compatibility

#169 修复无法使用“!reset+预设名” 的命令
  pkg/process/revss.py
Labels: bug, compatibility

#173 feat: 支持可选设置newbing的cookies
  README.md
  pkg/process/impls/edgegpt.py
Labels: bug, enhancement, compatibility
